package com.example.fincas_grupo3.domain.ports.in.estadopublicacion;


public interface EstadoPublicacionInPort extends ActualizarEstadoPublicacionUseCase, CrearEstadoPublicacionUseCase, EliminarEstadoPublicacionUseCase, ObtenerEstadoPublicacionUseCase{
}